### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by terencode** [velitasali/GTKTitleBar#1]
Hi, nice extension, here are some suggestions:
- Mention the github url in the description of the gnome-shell extension page so people can more easily contribute.
- Disable the debug info like `GTKTitleBar: windowDecoration - _toggleTitleBar + win: [object instance wrapper GType:MetaWindowX11 jsobj@0x7f80a8191550 native@0x55dba29a0b20]`

**Comment by velitasali** [comment]
Thanks for the suggestions.

**Comment by terencode** [comment]
Looking good, closing.
