### ISSUE TITLE
Hidden titlebar shown again after suspend

### ISSUE THREAD

**Issue by ddnexus** [velitasali/GTKTitleBar#11]
You have to manually re-hide each titlebar that reappear after a suspend.

**Comment by velitasali** [comment]
Hi @ddnexus,

This doesn't happen on my Ubuntu 19.04 installation. Do other extensions work correctly?

**Comment by ddnexus** [comment]
I reported it when I was still on 18.10, not sure whether the upgrade to 19.04 fixed it or something else but it works now. Thanks.
