### ISSUE TITLE
Spotify unable to be unmaximized

### ISSUE THREAD

**Issue by jacksongoode** [velitasali/GTKTitleBar#24]
On Ubuntu 20.04.

However, I'm not sure if this might be an issue that is aggravated by the Hide Top Bar extension (where some apps might think they've been put into a permanent full screen?) I've been using both as a way to remove the GTK title bar as well as the top bar for more available space. This has been [reported](https://askubuntu.com/questions/1200000/i-cant-exit-fullscreen-on-spotify-and-f11-just-skips-songs) in a few different places.

**Comment by velitasali** [comment]
Hello, I will release a newer version for GNOME 40 which won't be supported by older versions. Could you give feedback on that regarding this issue when it is possible?

**Comment by velitasali** [comment]
I am closing this issue due to the lack of response. Please feel free to reopen it if the problem persists!
