### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by peter-lyons-kehl** [velitasali/GTKTitleBar#28]
Hi Veli,

Summary: I've clicked "Upgrade" icon, restarted GNOME (and also whole Manjaro), but it still comes up with the "Upgrade" icon. No errors indicated. Repeated that several times over the last week or so.

https://extensions.gnome.org/local:
![image](https://user-images.githubusercontent.com/4270240/119554238-4e625580-bd51-11eb-835c-aa2645600395.png)

![image](https://user-images.githubusercontent.com/4270240/119554384-705bd800-bd51-11eb-884d-a0693f942419.png)

Please advise how I can help for you to reproduce this. GNOME 40.1.0 on current Manjaro.

**Comment by velitasali** [comment]
Hi Peter,

The shell requires a start to upgrade the extension, but I am guessing it doesn't work in your case.

You can also try this:
1. Delete the extension temporarily
2. Log out 
3. Log back in
4. Reinstall the extension

If that doesn't work (e.g. the extension remains installed even though you didn't reinstall it yet), I would guess it is installed as a system extension. In that case, you can check where it is located by: 

1. Press Alt + F2
2. Type `lg` and press Enter (this should open looking-glass)
3. Go to the **Extensions** tab from there
4. Find **GTK Title Bar**
5. Tab **View Source**

**Comment by peter-lyons-kehl** [comment]
Thank you for the steps.

I've uninstalled
![image](https://user-images.githubusercontent.com/4270240/119703280-3bac5700-be0b-11eb-9753-34afad2ed9bd.png)

Then I've logged out, logged in:
![image](https://user-images.githubusercontent.com/4270240/119704793-e8d39f00-be0c-11eb-8cbc-f64c177b0bc1.png)

Then I've re-installed:
![image](https://user-images.githubusercontent.com/4270240/119704903-03a61380-be0d-11eb-8c02-21ac9fd7d76b.png)

But, if immediately after reinstall I re-load https://extensions.gnome.org/extension/1732/gtk-title-bar, it shows the Update wheel icon:
![image](https://user-images.githubusercontent.com/4270240/119704975-1a4c6a80-be0d-11eb-8bde-1fda42ad69c6.png)

Alt+F2 > lg > extensions > GTK... > Source shows location `/home/pkehl/.local/share/gnome-shell/extensions`. After I uninstall, `gtktitlebar@velitasali.github.io` is not there anymore.

Alt+F2 > lg > extensions > GTK...  > Errors says: "gtktitlebar@velitasali.github.io has not emitted any errors".

I've tried that twice. Any tips, please?

**Comment by velitasali** [comment]
Not sure tbh. Are you sure it is installing the correct version and if so, could you check the version you have from the Extensions app?

The latest version should be **8**.

**Comment by peter-lyons-kehl** [comment]
Successfully updated to version 8 after Manjaro updated GNOME to 40.2.0.

Thank you.
