### ISSUE TITLE
Not working on GNOME 41

### ISSUE THREAD

**Issue by davelima** [velitasali/GTKTitleBar#29]
Hello

I have noted that although the extension installs without any error, the title bars keep showing. I have also tried some settings combinations but none seems to make any difference.

I'm using Fedora 35 with GNOME 41/Wayland with 2 screens.

Thank you!

**Comment by velitasali** [comment]
Hi,

I am also on GNOME 41/Wayland and the extension works. Could you specify the apps you are having issues with and whether those apps were working with the extension previously?

**Comment by davelima** [comment]
Thanks for the quick response @velitasali

I was reading the README and realized that my system was missing the `xprop` dependency. Just installed it and the extension worked fine.

**Comment by velitasali** [comment]
You are welcome :)
