### ISSUE TITLE
Using shortcuts to move windows across monitors does not toggle titlebar

### ISSUE THREAD

**Issue by 0ffz** [velitasali/GTKTitleBar#32]
Using a shortcut like `Super + Shift + Left/Right` to move windows across monitors will not update the titlebar. If it was hidden and the app is brought to a new monitor, the titlebar does not show until the window is unmaximized and maximized.

**Comment by velitasali** [comment]
I think that should fix the issue. Could you give it a try? If not, I will try it tomorrow.

**Comment by 0ffz** [comment]
Looks like it works, this is wonderful!

**Comment by 0ffz** [comment]
Hmm, actually after a bit of use, it seems like apps get into a state where they will hide the bar on other monitors and return it on the main one. I can't seem to reproduce it consistently but it seems to happen to everything after a bit of normal use, will follow up if I can.
