### ISSUE TITLE
PrefsWidget is already registered

### ISSUE THREAD

**Issue by wisnoskij** [velitasali/GTKTitleBar#33]
All I get is this error when opening the settings page.

`Error: Type name PrefsWidget is already registered

Stack trace:
  _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:444:27
  _init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:78:32
  registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
  @/home/wisnoskij/.local/share/gnome-shell/extensions/gtktitlebar@velitasali.github.io/prefs.js:5:29
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:216:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17`

**Comment by wisnoskij** [comment]
Fedora 35.
I have since seen in on other extensions, so it might just be gnome shell being broken

**Comment by velitasali** [comment]
Because extensions work in the same process, the name of GObject types they register should be unique. Simply put, there must be another extension that registers PrefsWidget and causing this error. That said, I am going to fix this by using a more _unique_ name.
