### ISSUE TITLE
Extension redraws titlebars for non gtk-apps that integrate titlebar

### ISSUE THREAD

**Issue by tim-hilt** [velitasali/GTKTitleBar#9]
Basically what the title states. When the extension is active and i maximize a window i get the desired behavior. However when i unmaximize the titlebar gets redrawn, i noticed the issue specifically for firefox and vscode.

![image](https://user-images.githubusercontent.com/16037579/57546902-de492880-735d-11e9-97da-94a44ee54cdc.png)

![image](https://user-images.githubusercontent.com/16037579/57546987-f620ac80-735d-11e9-9d57-7de038800f00.png)

![image](https://user-images.githubusercontent.com/16037579/57547028-0df83080-735e-11e9-90a3-100b6dcabf57.png)

**Comment by velitasali** [comment]
Hey, this is a duplicate of #6 . Also the solution was also merged and yet to be published on extensions.gnome.org.

In the mean time, you can download the contents of this repo and extract `gtktitlebar@velitasali.github.io` folder into `home/USERNAME/.local/share/gnome-shell/extensions` folder

ZIP file to download:
https://github.com/velitasali/GTKTitleBar/archive/master.zip

This is the change:
https://github.com/velitasali/GTKTitleBar/commit/da7512947401acd3a45a903714f7675c51c7f98a

**Comment by tim-hilt** [comment]
Thanks for pointing that out! Will switch to the git Version. Closing
